version: '3.8'

services:

  model-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet_fil_rouge_api-model-api-1
    ports:
      - "9500:8000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - HF_HOME=/app/cache 
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./.cache/huggingface:/app/cache

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks.worker_celery:celery_app worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - model-api
      - redis
    env_file:
      - .env
    environment:
      - HF_HOME=/app/cache
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./.cache/huggingface:/app/cache

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  huggingface_cache: